version: "3"
services:
  mysql:
    container_name: ca_tech_dojo_go
    image: mysql
    ports:
      - 3306:3306
    volumes:
      # docker-compose.ymlと同階層にある「initdb.d」という名前のディレクトリ配下の「.sql」「.sh」「.sql.gz」ファイルを実行
      - ./initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=ctdg
